apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spark-thrift-server-driver
spec:
  nodeSelector:
    type: karpenter
    provisioner: spark-driver
  tolerations:
    - key: spark-driver
      operator: Exists
      effect: NoSchedule
  containers:
    - name: spark-kubernetes-driver
